name: workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  go-toolchain:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Benchmark
      run: go test --bench=. --benchtime=10s -cpu 1 ./...

  bazel-toolchain:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: bazel build ...

    - name: Test
      run: bazel test ...

    - name: Benchmark 
      run: bazel test --test_output=streamed --test_arg=-test.v --test_arg=-test.bench=. --test_arg=-test.cpu=1  ...